In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as LA


In [12]:
A = np.array([[2,1,0],[1,2,1],[0,1,2]])
w, v = LA.eig(A)

In [5]:
# eigen values
print(w)

[3.41421356+0.j 2.        +0.j 0.58578644+0.j]


In [6]:
# eigen vectors
print(v)

[[-5.00000000e-01  7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01  4.05405432e-16 -7.07106781e-01]
 [-5.00000000e-01 -7.07106781e-01  5.00000000e-01]]


In [8]:
print(v.real)

[[-5.00000000e-01  7.07106781e-01  5.00000000e-01]
 [-7.07106781e-01  4.05405432e-16 -7.07106781e-01]
 [-5.00000000e-01 -7.07106781e-01  5.00000000e-01]]


In [9]:
A = np.array([[3,2,2], [2,3,2]])
print(A)
# SVD
U, s, VT = LA.svd(A)
print(U)
print(s)
print(VT)

[[3 2 2]
 [2 3 2]]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[5.74456265 1.        ]
[[-6.15457455e-01 -6.15457455e-01 -4.92365964e-01]
 [-7.07106781e-01  7.07106781e-01 -1.38777878e-17]
 [-3.48155312e-01 -3.48155312e-01  8.70388280e-01]]


In [37]:
mat31 = np.array([[0.082, 0.714],[0.082, -0.714]])
mat11 = np.array([[5.7, 0, 0],[0, 1, 0]]) 
mat21 = np.array([[0.07, 0.07, 0.058],[0.707, -0.707, 0],[-0.348, -0.348, 0.87]])
res1 = np.dot(mat31,np.dot(mat11,mat21))
print(res1)

[[ 0.537516  -0.47208    0.0271092]
 [-0.47208    0.537516   0.0271092]]


In [36]:
mat3 = np.array([[1.4, 1],[1.4,-1]])
mat1 = np.array([[5.7, 0, 0],[0, 1, 0]]) 
mat2 = np.array([[1.2, 1.2, 1],[1, -1, 0],[-0.4, -0.4, 1]]) 
res = np.dot(mat3,np.dot(mat1,mat2))
print(res)

[[10.576  8.576  7.98 ]
 [ 8.576 10.576  7.98 ]]


In [36]:
mat1 = np.array([[13, 12, 10],[12, 13, 10],[10, 10, 8]]) 
mat2 = np.array([[-0.4], [-0.4], [1]])
res = np.dot(mat1,mat2)
print(res)

[[0.]
 [0.]
 [0.]]


In [37]:
# mat3 = ([1.56, 1.6, 1])
b = 0
b*mat2

array([[-0.],
       [-0.],
       [ 0.]])

In [34]:
mat3 = np.array([[1.4, 1],[1.4,-1]])
# mat2 = np.array([[1.2, 1.2, 1],[1, -1, 0],[-0.4, -0.4, 1]]) 
mat4 = np.array([[1.2,1,-0.4],[1.2,-1,-0.4],[1,0,1]])
res1 = np.dot(mat3,mat4)
print(res)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [14]:
U, s, VT = LA.svd(res)
print(U)
print(s)
print(VT)

[[-0.28393812 -0.95884261]
 [-0.95884261  0.28393812]]
[8.5343253  3.58695548]
[[-0.55125257 -0.74200607  0.38150701]
 [-0.50167336 -0.07058715 -0.86217243]
 [-0.66666667  0.66666667  0.33333333]]


In [11]:
mat3=([[1/1.4, 1/1.4],[1.4,-1.4]])
mat1 = np.array([[5, 0, 0],[0, 3, 0]]) 
mat2 = np.array([[1/1.4, 1/1.4, 0],[1/4.2, -1/4.2, 4/4.2],[0.67, -0.67, 0.3]]) 
res = np.matmul(mat3,np.matmul(mat1,mat2))
print(res)

[[ 3.06122449  2.04081633  2.04081633]
 [ 4.          6.         -4.        ]]


In [5]:
1/

0.894736842105263

In [7]:
mat3=([[0.95, 5.4],[0.89,5.1]])
res2 = np.dot(mat3,res)

In [8]:
print(res2)

[[11.898   1.098   5.415 ]
 [11.1876  0.9876  5.073 ]]
